# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2025-04-16 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='number',
            new_name='email',
        ),
    ]
