# Generated by Django 3.2.25 on 2025-05-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='rate_number',
            field=models.FloatField(default=0),
        ),
    ]
