# Generated by Django 3.2.25 on 2025-04-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='contact_link',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='rate',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
