# Generated by Django 3.2.25 on 2025-05-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_rate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='rate_number',
            field=models.IntegerField(default=0),
        ),
    ]
