# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2025-04-17 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20250416_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='rate',
            field=models.FloatField(default=5.0),
        ),
    ]
