# Generated by Django 3.2.25 on 2025-05-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_userinfo_rate_number'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Conversation Time')),
                ('price', models.FloatField(default=0.0)),
                ('rate', models.IntegerField(default=5)),
                ('buyer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.productinfo')),
            ],
        ),
    ]
