# Generated by Django 3.2.25 on 2025-04-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=2000)),
                ('picture', models.ImageField(upload_to='product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posted_at', models.DateTimeField(blank=True, verbose_name='Conversation Time')),
                ('isSold', models.BooleanField(default=False)),
            ],
        ),
    ]
