# Generated by Django 3.2.25 on 2025-05-09 05:38

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=2000)),
                ('picture', models.ImageField(upload_to='product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Conversation Time')),
                ('isSold', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
            ],
            managers=[
                ('product', django.db.models.manager.Manager()),
            ],
        ),
    ]
