# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2025-04-17 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_rate'),
        ('product', '0002_auto_20250415_0941'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productinfo',
            managers=[
                ('product', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='productinfo',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
        ),
    ]
